[package]
name = "xor-rust"
version = "0.1.0"
authors = ["Kevin Pors <krpors@gmail.com>"]
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.12.1"
